def printDoc():
    print('\nSyntax :')
    print("-> Seperate parameters with underscore")
    print("-> Maintain the order of the parameters")
    print('---------------------------------------')
    print("-> Available combinations are :")
    print("------> 1 = Only Alphabetical(MixedCase)")
    print("------> 2 = Only Numerical(0-9)")
    print("------> 3 = Only Symbolic(/,$,..)")
    print("------> 12 = Alphabetical + Numerical")
    print("------> 23 = Numerical + Symbolic")
    print("------> 13 = Alphabetical + Symbolic")
    print("------> 123 = Alphabetical + Numerical + Symbolic")
    print("-> Order not required (132 is same as 123)")
    print('---------------------------------------')
    print('Parameters :')
    print("-> 1) Password Length [Min = 0 : Max = 20")
    print("-> 2) Password Type [Any combination as shown]")
    print("-> 3) Password Keyword [Optional]")
    print("-> 4) Keyword + Underscore [Optional]")
    print('---------------------------------------')
    print('Sample with Example :')
    print("-> 1) Let's say you enter 12_123")
    print("------> Password = 12 Characters long + 123 combination")
    print("------> Example = R*s7hmXTO6UJ)")
    print("-> 2) Let's say you enter 12_123_Keyword")
    print("------> Password = 12 Chr + 123 Cmb + Keyword in [MixedCase]")
    print("------> Example = KeYwoRd!+83G)")
    print("-> 3) Let's say you enter 12_123_Keyword_someLetters")
    print("------> Password = 12 Chr + 123 Cmb + [Keyword + Underscore]")
    print("------> Example = KeYwOrd_DJ*x)")
    print("-> Choose your type - Customize your password")
    print('---------------------------------------\n')